@echo off
echo Installing KEC Backend dependencies...
npm install
echo Dependencies installed!
echo Running database migration...
npx prisma migrate dev --name init
echo Database migrated!
echo Seeding database...
npx prisma db seed
echo Database seeded!
echo Starting server...
npm run dev